# -*- coding: utf-8 -*-
"""Emit the grade 10 Chapter 3 questions as an Apps Script seeding function.

Pasting 40 rows of LaTeX into Sheets by hand risks the locale turning
"-1/6" into a date, which would make that question permanently ungradeable.
Writing the rows from the script instead lets us force the answer columns to
plain text first, so the values land exactly as written.
"""
import io
import json
import sys

import week01
import week02
from emit import alternates

WEEKS = [('week-01', week01.Q), ('week-02', week02.Q)]
GRADE = '10'

HEADER = '''
/* =========================================================================
   One-time seed data: grade 10, Chapter 3 (Coordinate geometry) of
   Cambridge Pure Mathematics 1, split into two weeks to match the school's
   10th grade AS-level plan.

   Generated by homework/generator/emit_gs.py - edit the questions there and
   regenerate rather than hand-editing this block.
   ========================================================================= */

const GRADE_10_SEED_GRADE = '10';

const GRADE10_CH3_SEED = ['''

FOOTER = '''];

/**
 * Menu command: writes the grade 10 Chapter 3 questions into AnswerKey.
 *
 * Safe to re-run - it refuses to add a week that already has grade 10 rows,
 * so a second run cannot duplicate questions. The CorrectAnswer and Tolerance
 * columns are forced to plain text before writing, because answers such as
 * "-1/6" would otherwise be silently converted to a date or a decimal by
 * Sheets' locale parsing, and the question would then always grade wrong.
 */
function seedGrade10Chapter3() {
  const ui = SpreadsheetApp.getUi();
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(ANSWER_KEY_SHEET);
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];

  const gradeCol = headers.indexOf('Grade');
  if (gradeCol < 0) {
    ui.alert('AnswerKey has no "Grade" column yet.\\n\\nRun "First-time setup: 1) Init structure" once, then try this again.');
    return;
  }

  const weeksWanted = {};
  GRADE10_CH3_SEED.forEach(function (q) { weeksWanted[q.week] = true; });

  const existing = getAllWeekIds(GRADE_10_SEED_GRADE);
  const clash = Object.keys(weeksWanted).filter(function (w) { return existing.indexOf(w) !== -1; });
  if (clash.length > 0) {
    ui.alert('Grade ' + GRADE_10_SEED_GRADE + ' already has questions for: ' + clash.join(', ') +
      '.\\n\\nNothing was added. Delete those rows first if you want to re-seed.');
    return;
  }

  const idx = {
    weekId: headers.indexOf('WeekID'),
    questionId: headers.indexOf('QuestionID'),
    type: headers.indexOf('Type'),
    correct: headers.indexOf('CorrectAnswer'),
    tolerance: headers.indexOf('Tolerance'),
    points: headers.indexOf('Points'),
    hint: headers.indexOf('Hint'),
    solution: headers.indexOf('Solution'),
    title: headers.indexOf('Title'),
    choices: headers.indexOf('Choices')
  };
  const missing = Object.keys(idx).filter(function (k) { return idx[k] < 0; });
  if (missing.length > 0) {
    ui.alert('AnswerKey is missing these column headers: ' + missing.join(', ') + '. Nothing was added.');
    return;
  }

  const startRow = sheet.getLastRow() + 1;
  const rows = GRADE10_CH3_SEED.map(function (q) {
    const row = [];
    for (let c = 0; c < headers.length; c++) row.push('');
    row[idx.weekId] = q.week;
    row[gradeCol] = GRADE_10_SEED_GRADE;
    row[idx.questionId] = q.qid;
    row[idx.type] = q.type;
    row[idx.correct] = q.correct;
    row[idx.tolerance] = q.tolerance;
    row[idx.points] = q.points;
    row[idx.hint] = q.hint;
    row[idx.solution] = q.solution;
    row[idx.title] = q.title;
    row[idx.choices] = q.choices;
    return row;
  });

  // Plain text on the two columns whose values Sheets would otherwise
  // reinterpret ("-1/6" as a date, "0" as a formatted number).
  sheet.getRange(startRow, idx.correct + 1, rows.length, 1).setNumberFormat('@');
  sheet.getRange(startRow, idx.tolerance + 1, rows.length, 1).setNumberFormat('@');

  sheet.getRange(startRow, 1, rows.length, headers.length).setValues(rows);
  applyTypeValidation(sheet, startRow, rows.length);

  Object.keys(weeksWanted).forEach(function (w) {
    getOrCreateResponsesSheet(w, GRADE_10_SEED_GRADE);
  });

  ui.alert(
    'Added ' + rows.length + ' grade ' + GRADE_10_SEED_GRADE + ' questions ' +
    '(rows ' + startRow + '-' + (startRow + rows.length - 1) + ') for: ' +
    Object.keys(weeksWanted).sort().join(', ') + '.\\n\\n' +
    'Response sheets are ready. Students reach them at ' +
    '?week=week-01&grade=' + GRADE_10_SEED_GRADE + '.'
  );
}
'''


def js(value):
    """A JS string literal. JSON strings are valid JS, so this escapes safely."""
    return json.dumps(value, ensure_ascii=False)


def main(outpath):
    parts = [HEADER]
    for week, qs in WEEKS:
        parts.append('  // --- %s ---' % week)
        for q in qs:
            # Must match what emit.py writes into the TSV, or the two routes
            # would accept different answers for the same question.
            correct = q['CorrectAnswer']
            if q['Type'] == 'text':
                correct = '|'.join(dict.fromkeys(alternates(correct)))
            parts.append('  {')
            parts.append('    week: %s, qid: %s, type: %s,' % (js(week), js(q['QuestionID']), js(q['Type'])))
            parts.append('    correct: %s,' % js(correct))
            parts.append('    tolerance: %s, points: %s,' % (js(str(q['Tolerance'])), q['Points']))
            parts.append('    title: %s,' % js(q['Title']))
            parts.append('    choices: %s,' % js(q['Choices']))
            parts.append('    hint: %s,' % js(q['Hint']))
            parts.append('    solution: %s' % js(q['Solution']))
            parts.append('  },')
    parts.append(FOOTER)

    body = '\n'.join(parts)
    io.open(outpath, 'w', encoding='utf-8', newline='\n').write(body)
    n = sum(len(qs) for _, qs in WEEKS)
    print('wrote %s (%d questions, %d chars)' % (outpath, n, len(body)))


if __name__ == '__main__':
    main(sys.argv[1])
